preload = ["./.gyoza/tasks/preload.ts"]
jsx = "react-jsx"
logLevel = "info"
jsxImportSource = "react"

[define]
"Bun.GYOZA_TEMP_DIR" = "'.gyoza/.tmp'"

[loader]
".replit" = "toml"
".sql" = "sqlite"
".css" = "css"
".toml" = "toml"
".nu" = "text"
